### PR TITLE
Create mkradio3a.json

### PR DESCRIPTION
**Pull request by salaun29**
JSON for new mkradio3a driver

### CODE REVIEW

**Comment by BIBOLV** [comment]
Hi,
Please update only edge channel as everything from there is being overwritten to main, and also change `sw_version` to `hw_version` in code.

**Comment by salaun29** [comment]
Hi,

I changed the sw_version to hw_version as requested. How can I publish this on edge channel (I can't see it :) )? 

Yann,

**Comment by BIBOLV** [comment]
Use `wmbusmeters-ha-addon-edge` directory

**Comment by salaun29** [comment]
Replaced

**Comment by salaun29** [comment]
Done

**Pull request closed without merging**
