### PR TITLE
Add MQTT discovery for ABB B23 electricity meter

### PR DESCRIPTION
**Pull request by snapspizza**

### CODE REVIEW

**Comment by BIBOLV** [comment]
Thanks for PR!
Please place file in mqtt_discovery - alongside other template files.

**Comment by snapspizza** [comment]
Sorry about that. I'm new to this platform.

**Comment by BIBOLV** [comment]
That`s ok 😉 
Something wrong with HA build image, so new addon version will not be built now - will try later.

**Comment by BIBOLV** [comment]
Addon has been built

**Pull request merged**
